repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: mixed-line-ending
    -   id: requirements-txt-fixe
    -   id: check-merge-conflict
    -   id: check-docstring-first
-   repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3
    hooks:
    -   id: pycln
-   repo: https://github.com/pycqa/isort
    rev: v5.12.0
    hooks:
    -   id: isort
        entry: isort
        args:
        -   --profile
        -   black
        -   l 100
-   repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
    -   id: black
        name: black (python39)
        entry: black
        language: system
        types: [ python ]
        exclude: '.*.md|.*.rst'
        include: '^(methods|tests)/.*$'
        args:
        -   -l 100
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
        -   -rn
        -   -sn
        -   --rcfile=.pylintrc
